### ISSUE TITLE
convert-vapid-public-key can be not found

### ISSUE THREAD

**Issue by m91michel** [screendriver/convert-vapid-public-key#320]
Hey, thanks for maintaining this package!

Is there an error in your latest 2.0.0 release? 
Our latest Dependabot upgrade for convert-vapid-public-key fails due to this error. After checking this repo, I noticed that it is already using TypeScript, but you package can be not found by VSCode. And I could not find a hint that the import statement changed.

![image](https://github.com/screendriver/convert-vapid-public-key/assets/9262982/2c683a9d-0fd3-4a5d-b6c8-07bcedaace08)

## Tsconfig
```json
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "strictNullChecks": false,
    "jsx": "react-jsx",
    "declaration": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strict": false,
    "noFallthroughCasesInSwitch": true
  },
  "include": [
    "src"
  ]
}
```

**Comment by screendriver** [comment]
Hi,

the package is [now pure ECMAScript modules (ESM)](https://github.com/screendriver/convert-vapid-public-key/releases/tag/v2.0.0) and cannot be `require()`ed from `CommonJS` anymore.

You have to change your repository to [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) as well. You can read more about how to do it [here](https://www.typescriptlang.org/docs/handbook/esm-node.html) or [here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) for example.

**Comment by m91michel** [comment]
We are importing this package with `import convertVapidKey from "convert-vapid-public-key"` so our projects already handles ESM modules.

**Comment by m91michel** [comment]
Thanks for detailed explanation. As our projects has some other dependencies, we can not switch to full ESM project. At least this is a bigger task, which needs a bit of planning. 

Until then, we are just staying at version 1.x 😊

**Comment by screendriver** [comment]
You're welcome 🙂

You can still use v1 because there is no difference between both versions except the underlying module system. Functionality is exactly the same 😉
